// src/troxtmod3d/preloadedCharacters.js
// ETHERWORLD RP — 18 personnages préchargés GTA-RP

import { DEFAULT_STATE, DEFAULT_RP_PROFILE } from './constants';

const mkRp = (partial) => ({
  ...DEFAULT_RP_PROFILE,
  ...partial,
  licenses: { ...DEFAULT_RP_PROFILE.licenses, ...(partial.licenses || {}) },
});

export const PRELOADED_CHARACTERS = [
  // ═══ MÉTIERS DU QUÉBEC ═══
  {
    id: 'garde_forestier', name: 'Marc-André Tremblay', jobTitle: 'Garde Forestier MFFP',
    category: 'Métiers du Québec',
    description: 'Agent assermenté pour la protection de la faune boréale.',
    avatarIcon: '🌲', tagColor: 'from-emerald-600 to-green-800', badge: 'MFFP QUÉBEC',
    defaultAura: null,
    state: {
      ...DEFAULT_STATE, name: 'Marc-André Tremblay', nationality: 'canadian',
      skin: 2, hairStyle: 1, hairColor: 2, facialHair: 4,
      height: 58, muscular: 65, fatness: 25,
      topStyle: 4, topColor: 4, pantsStyle: 4, pantsColor: 7,
      shoesStyle: 5, shoesColor: 8, hatStyle: 1, hatColor: 4,
      backpackStyle: 2, watchStyle: 3, activeAura: null,
      rp: mkRp({
        age: 42, district: 'saguenay',
        job: 'forestier', jobTitle: 'Garde forestier', employer: 'MFFP Québec', salary: 32,
        gang: 'aucun', criminalRecord: 'vierge', wantedLevel: 0,
        cash: 380, bank: 18500,
        licenses: { conduire: true, armes: true, chasse: true, peche: true },
        vehicleType: 'pickup', vehicleModel: 'Ford F-150', vehicleColor: '#1e3a1e',
        phone: '418-555-0198',
        backstory: 'Vétéran du MFFP, 18 ans de service en forêt boréale.',
        goals: 'Protéger la faune et former les nouvelles recrues.',
      }),
    },
  },
  {
    id: 'bucheron_boreal', name: 'Jean-Guy Bouchard', jobTitle: 'Bûcheron des Laurentides',
    category: 'Métiers du Québec',
    description: 'Exploitant forestier chevronné de la Mauricie.',
    avatarIcon: '🪓', tagColor: 'from-amber-700 to-stone-800', badge: 'BOIS DU NORD',
    defaultAura: null,
    state: {
      ...DEFAULT_STATE, name: 'Jean-Guy Bouchard', nationality: 'canadian',
      skin: 3, hairStyle: 3, hairColor: 3, facialHair: 4,
      height: 62, muscular: 75, fatness: 35,
      topStyle: 1, topColor: 5, pantsStyle: 0, pantsColor: 1,
      shoesStyle: 1, shoesColor: 8, hatStyle: 2, hatColor: 0,
      backpackStyle: 1, watchStyle: 0,
      rp: mkRp({
        age: 51, district: 'trois_rivieres',
        job: 'forestier', jobTitle: 'Bûcheron', employer: 'Bois du Nord Inc.', salary: 28,
        gang: 'aucun', criminalRecord: 'mineur', wantedLevel: 0,
        cash: 250, bank: 12000,
        licenses: { conduire: true, chasse: true, peche: true },
        vehicleType: 'pickup', vehicleModel: 'Chevrolet Silverado', vehicleColor: '#6a3020',
        phone: '819-555-0341',
        backstory: 'Fils de bûcheron, travaille la forêt depuis 30 ans.',
        goals: 'Transmettre le métier à son fils.',
      }),
    },
  },
  {
    id: 'biologiste_faune', name: 'Dr. Émilie Lavallée', jobTitle: 'Biologiste Spécialiste Faune',
    category: 'Métiers du Québec',
    description: 'Chercheuse en écologie comportementale.',
    avatarIcon: '🔬', tagColor: 'from-teal-600 to-emerald-900', badge: 'BIO-RECHERCHE',
    defaultAura: 'void',
    state: {
      ...DEFAULT_STATE, gender: 'female', name: 'Dr. Émilie Lavallée', nationality: 'canadian',
      skin: 1, hairStyle: 5, hairColor: 3, facialHair: 0,
      height: 48, muscular: 42, fatness: 20,
      topStyle: 0, topColor: 6, pantsStyle: 1, pantsColor: 7,
      shoesStyle: 0, shoesColor: 10, glassesStyle: 2, glassesColor: 0,
      backpackStyle: 1, watchStyle: 2, activeAura: null,
      rp: mkRp({
        age: 34, district: 'plateau',
        job: 'ingenieur', jobTitle: 'Biologiste chercheuse', employer: 'Université Laval', salary: 58,
        gang: 'aucun', criminalRecord: 'vierge', wantedLevel: 0,
        cash: 120, bank: 24000,
        licenses: { conduire: true, peche: true },
        vehicleType: 'suv', vehicleModel: 'Subaru Outback', vehicleColor: '#1e3a1e',
        phone: '514-555-0723',
        backstory: 'Doctorat en écologie, passionnée par les grands prédateurs.',
        goals: 'Publier une étude majeure sur les loups du Québec.',
      }),
    },
  },
  {
    id: 'policier_montreal', name: 'Agent Sophie Bergeron', jobTitle: 'Policière SPVM',
    category: 'Métiers du Québec',
    description: 'Patrouilleuse du Service de Police de la Ville de Montréal.',
    avatarIcon: '👮‍♀️', tagColor: 'from-blue-600 to-indigo-800', badge: 'SPVM',
    defaultAura: null,
    state: {
      ...DEFAULT_STATE, gender: 'female', name: 'Agent Sophie Bergeron', nationality: 'canadian',
      skin: 1, hairStyle: 9, hairColor: 3, facialHair: 0,
      height: 50, muscular: 55, fatness: 22,
      topStyle: 8, topColor: 0, pantsStyle: 0, pantsColor: 0,
      shoesStyle: 5, shoesColor: 0, hatStyle: 4, hatColor: 0,
      glassesStyle: 1, glassesColor: 0, watchStyle: 1,
      rp: mkRp({
        age: 29, district: 'montreal_nord',
        job: 'spvm', jobTitle: 'Agente de patrouille', employer: 'SPVM', salary: 45,
        gang: 'aucun', criminalRecord: 'vierge', wantedLevel: 0,
        cash: 340, bank: 8900,
        licenses: { conduire: true, armes: true },
        vehicleType: 'sedan', vehicleModel: 'Ford Taurus Interceptor', vehicleColor: '#1a3a8c',
        phone: '514-555-1200',
        backstory: 'Diplômée de l\'École nationale de police du Québec.',
        goals: 'Devenir détective au SPVM.',
      }),
    },
  },
  {
    id: 'pompier_mtl', name: 'Capitaine Luc Rivard', jobTitle: 'Capitaine Pompier SIM',
    category: 'Métiers du Québec',
    description: 'Chef d\'intervention du Service Incendie de Montréal.',
    avatarIcon: '🚒', tagColor: 'from-red-600 to-orange-800', badge: 'SIM POMPIERS',
    defaultAura: 'fire',
    state: {
      ...DEFAULT_STATE, name: 'Capitaine Luc Rivard', nationality: 'canadian',
      skin: 2, hairStyle: 0, hairColor: 0, facialHair: 3,
      height: 60, muscular: 70, fatness: 28,
      topStyle: 8, topColor: 5, pantsStyle: 5, pantsColor: 0,
      shoesStyle: 5, shoesColor: 0, hatStyle: 1, hatColor: 5,
      watchStyle: 3, activeAura: 'fire',
      rp: mkRp({
        age: 45, district: 'rosemont',
        job: 'pompier', jobTitle: 'Capitaine', employer: 'SIM Montréal', salary: 52,
        gang: 'aucun', criminalRecord: 'vierge', wantedLevel: 0,
        cash: 500, bank: 32000,
        licenses: { conduire: true, armes: false },
        vehicleType: 'pickup', vehicleModel: 'Ford F-250', vehicleColor: '#aa0000',
        phone: '514-555-0911',
        backstory: '22 ans de service, héros du feu de l\'entrepôt Mile-End.',
        goals: 'Former la prochaine génération de pompiers.',
      }),
    },
  },
  {
    id: 'ambulancier', name: 'Paramédic Isabelle Roy', jobTitle: 'Paramédic Urgences-Santé',
    category: 'Métiers du Québec',
    description: 'Paramédic d\'urgence sur le territoire de Montréal.',
    avatarIcon: '🚑', tagColor: 'from-rose-600 to-red-800', badge: 'URGENCES-SANTÉ',
    defaultAura: null,
    state: {
      ...DEFAULT_STATE, gender: 'female', name: 'Paramédic Isabelle Roy', nationality: 'canadian',
      skin: 0, hairStyle: 7, hairColor: 6, facialHair: 0,
      height: 52, muscular: 48, fatness: 22,
      topStyle: 6, topColor: 10, pantsStyle: 5, pantsColor: 0,
      shoesStyle: 0, shoesColor: 10, glassesStyle: 0, hatStyle: 0,
      watchStyle: 2,
      rp: mkRp({
        age: 31, district: 'longueuil',
        job: 'ems', jobTitle: 'Paramédic', employer: 'Urgences-Santé', salary: 40,
        gang: 'aucun', criminalRecord: 'vierge', wantedLevel: 0,
        cash: 280, bank: 11200,
        licenses: { conduire: true, armes: false },
        vehicleType: 'van', vehicleModel: 'Ambulance Demers', vehicleColor: '#ffffff',
        phone: '450-555-0067',
        backstory: 'Ancienne militaire, reconvertie dans les soins d\'urgence.',
        goals: 'Sauver le plus de vies possible sur la Rive-Sud.',
      }),
    },
  },

  // ═══ SÉCURITÉ & URGENCES ═══
  {
    id: 'patrouilleur_sq', name: 'Sergent Maxime Gagnon', jobTitle: 'Patrouilleur Sûreté du Québec',
    category: 'Sécurité & Urgences',
    description: 'Policier d\'intervention d\'urgence sur la Route 138.',
    avatarIcon: '🚓', tagColor: 'from-blue-700 to-indigo-900', badge: 'SÛRETÉ DU QUÉBEC',
    defaultAura: 'lich_king',
    state: {
      ...DEFAULT_STATE, name: 'Sgt. Maxime Gagnon', nationality: 'canadian',
      skin: 1, hairStyle: 0, hairColor: 0, facialHair: 0,
      height: 55, muscular: 60, fatness: 22,
      topStyle: 8, topColor: 0, pantsStyle: 0, pantsColor: 0,
      shoesStyle: 5, shoesColor: 0, hatStyle: 4, hatColor: 0,
      glassesStyle: 1, glassesColor: 0, watchStyle: 1, activeAura: 'lich_king',
      rp: mkRp({
        age: 38, district: 'quebec_city',
        job: 'sq', jobTitle: 'Sergent', employer: 'Sûreté du Québec', salary: 52,
        gang: 'aucun', criminalRecord: 'vierge', wantedLevel: 0,
        cash: 420, bank: 18700,
        licenses: { conduire: true, armes: true },
        vehicleType: 'suv', vehicleModel: 'Ford Explorer PI', vehicleColor: '#1a3a8c',
        phone: '418-555-2200',
        backstory: '15 ans de service, spécialiste en intervention tactique.',
        goals: 'Devenir lieutenant avant 45 ans.',
      }),
    },
  },
  {
    id: 'swat_elite', name: 'Chef Martin Côté', jobTitle: 'Chef GTI SWAT',
    category: 'Sécurité & Urgences',
    description: 'Chef du Groupe Tactique d\'Intervention.',
    avatarIcon: '🎯', tagColor: 'from-slate-700 to-black', badge: 'GTI SWAT',
    defaultAura: 'shadow',
    state: {
      ...DEFAULT_STATE, name: 'Chef Martin Côté', nationality: 'canadian',
      skin: 2, hairStyle: 0, hairColor: 0, facialHair: 1,
      height: 58, muscular: 80, fatness: 22,
      topStyle: 8, topColor: 0, pantsStyle: 4, pantsColor: 0,
      shoesStyle: 5, shoesColor: 0, hatStyle: 8, hatColor: 0,
      glassesStyle: 4, glassesColor: 0, jewelryStyle: 3, watchStyle: 3,
      activeAura: 'shadow',
      rp: mkRp({
        age: 41, district: 'montreal_nord',
        job: 'spvm', jobTitle: 'Chef GTI', employer: 'SPVM - GTI', salary: 68,
        gang: 'aucun', criminalRecord: 'vierge', wantedLevel: 0,
        cash: 800, bank: 45000,
        licenses: { conduire: true, armes: true, vol: true },
        vehicleType: 'suv', vehicleModel: 'Lenco BearCat', vehicleColor: '#000000',
        phone: '514-555-8888',
        backstory: 'Ex-militaire, leader du GTI depuis 6 ans.',
        goals: 'Ne perdre aucun homme sous son commandement.',
      }),
    },
  },
  {
    id: 'garde_cote', name: 'Garde-Côte Amélie Roy', jobTitle: 'Garde-Côtière Canadienne',
    category: 'Sécurité & Urgences',
    description: 'Patrouille maritime du Saint-Laurent.',
    avatarIcon: '⚓', tagColor: 'from-cyan-600 to-blue-900', badge: 'GARDE-CÔTIÈRE',
    defaultAura: null,
    state: {
      ...DEFAULT_STATE, gender: 'female', name: 'GC Amélie Roy', nationality: 'canadian',
      skin: 1, hairStyle: 9, hairColor: 3, facialHair: 0,
      height: 53, muscular: 62, fatness: 24,
      topStyle: 6, topColor: 0, pantsStyle: 5, pantsColor: 0,
      shoesStyle: 5, shoesColor: 0, hatStyle: 1, hatColor: 0,
      watchStyle: 3,
      rp: mkRp({
        age: 36, district: 'rimouski',
        job: 'grc', jobTitle: 'Officière Garde-Côtière', employer: 'Garde-côtière canadienne', salary: 58,
        gang: 'aucun', criminalRecord: 'vierge', wantedLevel: 0,
        cash: 350, bank: 21000,
        licenses: { conduire: true, armes: true, bateau: true },
        vehicleType: 'bateau', vehicleModel: 'CCGS Cap Tourmente', vehicleColor: '#ffffff',
        phone: '418-555-7777',
        backstory: 'Ancienne navigatrice, spécialiste des eaux du Saint-Laurent.',
        goals: 'Intercepter les trafics maritimes.',
      }),
    },
  },

  // ═══ CYBER & FUTURISTE ═══
  {
    id: 'cyber_citoyen', name: 'Nova Crystal-99', jobTitle: 'Cyber-Citadin TroxT 2099',
    category: 'Cyber & Futuriste',
    description: 'Pionnier transhumain équipé d\'armures en graphène.',
    avatarIcon: '⚡', tagColor: 'from-fuchsia-600 to-cyan-600', badge: 'CYBER TROXT',
    defaultAura: 'cyber',
    state: {
      ...DEFAULT_STATE, name: 'Nova Crystal-99', nationality: 'canadian',
      skin: 0, hairStyle: 4, hairColor: 12, facialHair: 0,
      height: 52, muscular: 55, fatness: 15,
      topStyle: 5, topColor: 9, pantsStyle: 5, pantsColor: 9,
      shoesStyle: 4, shoesColor: 1, glassesStyle: 4, glassesColor: 0,
      jewelryStyle: 2, backpackStyle: 4, watchStyle: 2, activeAura: 'cyber',
      rp: mkRp({
        age: 27, district: 'montreal_nord',
        job: 'ingenieur', jobTitle: 'Ingénieur cybernétique', employer: 'TroxT Corp', salary: 92,
        gang: 'aucun', criminalRecord: 'vierge', wantedLevel: 0,
        cash: 2500, bank: 89000,
        licenses: { conduire: true, vol: true },
        vehicleType: 'supercar', vehicleModel: 'TroxT Hover-9', vehicleColor: '#aa55ff',
        phone: '438-555-0099',
        backstory: 'Cobaye volontaire du programme Transhumaniste TroxT.',
        goals: 'Repousser les limites du corps humain.',
      }),
    },
  },
  {
    id: 'hacker_neon', name: 'Zéro-Phantom', jobTitle: 'Hacker de l\'Ombre',
    category: 'Cyber & Futuriste',
    description: 'Pirate informatique traquant les mégacorporations.',
    avatarIcon: '💻', tagColor: 'from-purple-700 to-indigo-900', badge: 'NEON HACKER',
    defaultAura: 'cyber',
    state: {
      ...DEFAULT_STATE, gender: 'female', name: 'Zéro-Phantom', nationality: 'canadian',
      skin: 4, hairStyle: 0, hairColor: 12, facialHair: 0,
      height: 50, muscular: 40, fatness: 18,
      topStyle: 4, topColor: 0, pantsStyle: 3, pantsColor: 9,
      shoesStyle: 4, shoesColor: 0, glassesStyle: 4, glassesColor: 0,
      jewelryStyle: 2, backpackStyle: 4, watchStyle: 2, activeAura: 'cyber',
      rp: mkRp({
        age: 23, district: 'plateau',
        job: 'streamer', jobTitle: 'Hacker freelance', employer: 'Indépendante', salary: 0,
        gang: 'aucun', criminalRecord: 'majeur', wantedLevel: 3,
        cash: 8400, bank: 15000,
        licenses: { conduire: true },
        vehicleType: 'sport', vehicleModel: 'Kawasaki Ninja', vehicleColor: '#aa55ff',
        phone: '514-555-4242',
        backstory: 'Traquée par les mégacorps après avoir fuité leurs secrets.',
        goals: 'Faire tomber TroxT Corp.',
      }),
    },
  },
  {
    id: 'androide_police', name: 'Unité AX-7', jobTitle: 'Androïde Tactique Police',
    category: 'Cyber & Futuriste',
    description: 'Unité de police robotique de nouvelle génération.',
    avatarIcon: '🤖', tagColor: 'from-slate-500 to-gray-800', badge: 'POLICE AX',
    defaultAura: 'lightning',
    state: {
      ...DEFAULT_STATE, name: 'AX-7', nationality: 'canadian',
      skin: 5, hairStyle: 8, hairColor: 0, facialHair: 0,
      height: 56, muscular: 75, fatness: 20,
      topStyle: 7, topColor: 0, pantsStyle: 5, pantsColor: 0,
      shoesStyle: 5, shoesColor: 0, glassesStyle: 5, glassesColor: 0,
      watchStyle: 2, activeAura: 'lightning',
      rp: mkRp({
        age: 3, district: 'montreal_nord',
        job: 'spvm', jobTitle: 'Unité AX (androïde)', employer: 'SPVM - Division Cyber', salary: 0,
        gang: 'aucun', criminalRecord: 'vierge', wantedLevel: 0,
        cash: 0, bank: 0,
        licenses: { conduire: true, armes: true, vol: true },
        vehicleType: 'suv', vehicleModel: 'Patrouilleur AX-9', vehicleColor: '#555555',
        phone: '000-000-0000',
        backstory: 'Androïde de 3e génération, mis en service il y a 8 mois.',
        goals: 'Protéger et servir — Prime Directive.',
      }),
    },
  },
  {
    id: 'pilote_neon', name: 'Racer Kira', jobTitle: 'Pilote Cyber-Course',
    category: 'Cyber & Futuriste',
    description: 'Championne de course urbaine néon.',
    avatarIcon: '🏎️', tagColor: 'from-pink-500 to-yellow-500', badge: 'NEON RACER',
    defaultAura: 'sonic',
    state: {
      ...DEFAULT_STATE, gender: 'female', name: 'Racer Kira', nationality: 'japanese',
      skin: 1, hairStyle: 9, hairColor: 5, facialHair: 0,
      height: 50, muscular: 55, fatness: 18,
      topStyle: 14, topColor: 5, pantsStyle: 3, pantsColor: 0,
      shoesStyle: 4, shoesColor: 5, glassesStyle: 4, glassesColor: 1,
      watchStyle: 2, activeAura: 'sonic',
      rp: mkRp({
        age: 26, district: 'laval',
        job: 'chauffeur_bus', jobTitle: 'Pilote professionnelle', employer: 'Team Neon', salary: 0,
        gang: 'aucun', criminalRecord: 'mineur', wantedLevel: 1,
        cash: 3200, bank: 45000,
        licenses: { conduire: true, vol: true },
        vehicleType: 'supercar', vehicleModel: 'Nissan Skyline R34', vehicleColor: '#ff4488',
        phone: '450-555-3300',
        backstory: 'Championne de 3 tournois de course clandestine.',
        goals: 'Gagner le Championnat Mondial Neon.',
      }),
    },
  },

  // ═══ ÉLITE & PRESTIGE ═══
  {
    id: 'architecte_ether', name: 'Lord Valérian d\'Éther', jobTitle: 'Architecte Céleste EtherWorld',
    category: 'Élite & Prestige',
    description: 'Maître d\'œuvre de la cité virtuelle.',
    avatarIcon: '👑', tagColor: 'from-amber-400 to-yellow-600', badge: 'FONDATEUR VIP',
    defaultAura: 'holy',
    state: {
      ...DEFAULT_STATE, name: 'Lord Valérian', nationality: 'french',
      skin: 0, hairStyle: 5, hairColor: 6, facialHair: 0,
      height: 50, muscular: 40, fatness: 18,
      topStyle: 2, topColor: 10, pantsStyle: 3, pantsColor: 10,
      shoesStyle: 6, shoesColor: 7, glassesStyle: 5, glassesColor: 1,
      hatStyle: 5, hatColor: 1, jewelryStyle: 1, watchStyle: 1, activeAura: 'holy',
      rp: mkRp({
        age: 52, district: 'plateau',
        job: 'patron', jobTitle: 'Architecte en chef', employer: 'EtherWorld Corp', salary: 250,
        gang: 'aucun', criminalRecord: 'vierge', wantedLevel: 0,
        cash: 50000, bank: 2500000,
        licenses: { conduire: true, armes: false, vol: true, bateau: true },
        vehicleType: 'supercar', vehicleModel: 'Rolls-Royce Phantom', vehicleColor: '#ffffff',
        phone: '514-555-0001',
        backstory: 'Fondateur visionnaire d\'EtherWorld, mécène des arts.',
        goals: 'Bâtir la plus grande ville virtuelle du monde.',
      }),
    },
  },
  {
    id: 'roi_demon', name: 'Roi Malakar', jobTitle: 'Souverain des Enfers',
    category: 'Élite & Prestige',
    description: 'Seigneur démoniaque régnant sur les Neuf Enfers.',
    avatarIcon: '😈', tagColor: 'from-red-700 to-black', badge: 'ROI DÉMON',
    defaultAura: 'infernal',
    state: {
      ...DEFAULT_STATE, name: 'Roi Malakar', nationality: 'other',
      skin: 4, hairStyle: 3, hairColor: 10, facialHair: 4,
      height: 62, muscular: 90, fatness: 28,
      topStyle: 9, topColor: 10, pantsStyle: 5, pantsColor: 0,
      shoesStyle: 1, shoesColor: 0, hatStyle: 5, hatColor: 5,
      jewelryStyle: 1, watchStyle: 1, activeAura: 'infernal',
      rp: mkRp({
        age: 999, district: 'montreal_nord',
        job: 'criminel', jobTitle: 'Roi du crime', employer: 'Les Neuf Enfers', salary: 0,
        gang: 'mafia_italienne', gangRank: 'Parrain',
        criminalRecord: 'fichier', wantedLevel: 5,
        cash: 999999, bank: 5000000,
        licenses: { conduire: true, armes: true, vol: true, bateau: true },
        vehicleType: 'supercar', vehicleModel: 'Lamborghini Diablo', vehicleColor: '#aa0000',
        phone: '666-666-6666',
        backstory: 'Règne depuis des millénaires sur le crime organisé.',
        goals: 'Étendre son empire au monde des vivants.',
      }),
    },
  },
  {
    id: 'divinite_ange', name: 'Séraphin Uriel', jobTitle: 'Gardien Céleste',
    category: 'Élite & Prestige',
    description: 'Messager divin armé de la lumière sacrée.',
    avatarIcon: '😇', tagColor: 'from-yellow-200 to-amber-400', badge: 'SÉRAPHIN',
    defaultAura: 'celestial',
    state: {
      ...DEFAULT_STATE, name: 'Séraphin Uriel', nationality: 'other',
      skin: 5, hairStyle: 5, hairColor: 6, facialHair: 0,
      height: 58, muscular: 55, fatness: 15,
      topStyle: 6, topColor: 10, pantsStyle: 5, pantsColor: 10,
      shoesStyle: 6, shoesColor: 7, glassesStyle: 0,
      jewelryStyle: 2, watchStyle: 0, activeAura: 'celestial',
      rp: mkRp({
        age: 9999, district: 'montreal_sud',
        job: 'avocat', jobTitle: 'Messager divin', employer: 'Chœurs célestes', salary: 0,
        gang: 'aucun', criminalRecord: 'vierge', wantedLevel: 0,
        cash: 0, bank: 0,
        licenses: { conduire: true, vol: true },
        vehicleType: 'aucun', vehicleModel: 'Ailes célestes', vehicleColor: '#ffffff',
        phone: '777-777-7777',
        backstory: 'Messager de la lumière, protecteur des innocents.',
        goals: 'Maintenir l\'équilibre entre les mondes.',
      }),
    },
  },
  {
    id: 'liche_ancien', name: 'Archiliche Vorath', jobTitle: 'Seigneur de la Non-Vie',
    category: 'Élite & Prestige',
    description: 'Nécromancien millénaire commandant les morts.',
    avatarIcon: '💀', tagColor: 'from-slate-700 to-purple-900', badge: 'ARCHILICHE',
    defaultAura: 'necrotic',
    state: {
      ...DEFAULT_STATE, name: 'Archiliche Vorath', nationality: 'other',
      skin: 6, hairStyle: 8, hairColor: 0, facialHair: 4,
      height: 55, muscular: 40, fatness: 20,
      topStyle: 9, topColor: 0, pantsStyle: 5, pantsColor: 0,
      shoesStyle: 1, shoesColor: 0, hatStyle: 7, hatColor: 0,
      jewelryStyle: 3, watchStyle: 0, activeAura: 'necrotic',
      rp: mkRp({
        age: 1450, district: 'saguenay',
        job: 'criminel', jobTitle: 'Nécromancien', employer: 'Culte de Vorath', salary: 0,
        gang: 'cartel_mexicain', gangRank: 'Grand Prêtre',
        criminalRecord: 'fichier', wantedLevel: 4,
        cash: 45000, bank: 800000,
        licenses: { conduire: true, armes: true },
        vehicleType: 'helico', vehicleModel: 'Corbeau spectral', vehicleColor: '#4c1d95',
        phone: '000-000-0666',
        backstory: 'Nécromancien immortel, a pactisé avec les ténèbres.',
        goals: 'Réveiller l\'armée des morts.',
      }),
    },
  },
  {
    id: 'dragon_lord', name: 'Drakthar le Rouge', jobTitle: 'Seigneur-Dragon',
    category: 'Élite & Prestige',
    description: 'Dragon ancestral sous forme humanoïde.',
    avatarIcon: '🐉', tagColor: 'from-red-800 to-yellow-700', badge: 'DRAGON LORD',
    defaultAura: 'fire',
    state: {
      ...DEFAULT_STATE, name: 'Drakthar', nationality: 'other',
      skin: 6, hairStyle: 0, hairColor: 11, facialHair: 3,
      height: 65, muscular: 85, fatness: 30,
      topStyle: 7, topColor: 5, pantsStyle: 5, pantsColor: 10,
      shoesStyle: 1, shoesColor: 7, glassesStyle: 0,
      jewelryStyle: 1, watchStyle: 0, activeAura: 'fire',
      rp: mkRp({
        age: 500, district: 'montreal_nord',
        job: 'patron', jobTitle: 'Chef de clan', employer: 'Clan Draconique', salary: 180,
        gang: 'mafia_russe', gangRank: 'Chef',
        criminalRecord: 'majeur', wantedLevel: 4,
        cash: 120000, bank: 1500000,
        licenses: { conduire: true, armes: true, vol: true, bateau: true },
        vehicleType: 'supercar', vehicleModel: 'Ferrari SF90', vehicleColor: '#aa0000',
        phone: '514-555-6666',
        backstory: 'Dragon ancestral incarné en humain pour dominer le crime.',
        goals: 'Récupérer son trésor perdu.',
      }),
    },
  },
];