-- Migration 002: Players & Characters
-- Tables: players, characters

CREATE TABLE IF NOT EXISTS `players` (
  `id` CHAR(36) PRIMARY KEY,
  `steam_id` VARCHAR(32) UNIQUE,
  `discord_id` VARCHAR(32) UNIQUE,
  `email` VARCHAR(255) UNIQUE,
  `password_hash` VARCHAR(255) NOT NULL,
  `username` VARCHAR(64) NOT NULL UNIQUE,
  `role` ENUM('user','moderator','admin','owner') DEFAULT 'user',
  `status` ENUM('active','banned','suspended') DEFAULT 'active',
  `ip_last` VARCHAR(45),
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `last_login` TIMESTAMP NULL,
  `playtime_seconds` INT UNSIGNED DEFAULT 0,
  INDEX `idx_role` (`role`),
  INDEX `idx_status` (`status`),
  INDEX `idx_created` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `characters` (
  `id` CHAR(36) PRIMARY KEY,
  `player_id` CHAR(36) NOT NULL,
  `ew_id` VARCHAR(16) NOT NULL UNIQUE,
  `first_name` VARCHAR(32) NOT NULL,
  `last_name` VARCHAR(32) NOT NULL,
  `full_name` VARCHAR(64) GENERATED ALWAYS AS (CONCAT(`first_name`,' ',`last_name`)) STORED,
  `gender` ENUM('male','female') NOT NULL,
  `nationality` VARCHAR(32) DEFAULT 'canadian',
  `skin_tone` TINYINT UNSIGNED DEFAULT 1,
  `face_shape` TINYINT UNSIGNED DEFAULT 0,
  `eye_color` TINYINT UNSIGNED DEFAULT 0,
  `hair_style` TINYINT UNSIGNED DEFAULT 1,
  `hair_color` TINYINT UNSIGNED DEFAULT 0,
  `body_type` TINYINT UNSIGNED DEFAULT 1,
  `height` TINYINT UNSIGNED DEFAULT 50,
  `muscular` TINYINT UNSIGNED DEFAULT 45,
  `fatness` TINYINT UNSIGNED DEFAULT 30,
  `top_style` TINYINT UNSIGNED DEFAULT 0,
  `top_color` TINYINT UNSIGNED DEFAULT 1,
  `pants_style` TINYINT UNSIGNED DEFAULT 0,
  `pants_color` TINYINT UNSIGNED DEFAULT 1,
  `shoes_style` TINYINT UNSIGNED DEFAULT 0,
  `shoes_color` TINYINT UNSIGNED DEFAULT 0,
  `position_x` FLOAT DEFAULT 0,
  `position_y` FLOAT DEFAULT 5,
  `position_z` FLOAT DEFAULT 0,
  `rotation` FLOAT DEFAULT 0,
  `health` TINYINT UNSIGNED DEFAULT 100,
  `money` DECIMAL(15,2) DEFAULT 2500.00,
  `bank` DECIMAL(15,2) DEFAULT 0.00,
  `job_id` VARCHAR(32) DEFAULT 'unemployed',
  `active_aura` VARCHAR(32) NULL,
  `unlocked_auras` JSON DEFAULT ('[]'),
  `is_online` BOOLEAN DEFAULT FALSE,
  `last_saved` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (`player_id`) REFERENCES `players`(`id`) ON DELETE CASCADE,
  INDEX `idx_player` (`player_id`),
  INDEX `idx_name` (`full_name`),
  INDEX `idx_online` (`is_online`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;